### ISSUE TITLE
Bump Java, and Scala versions. 

### ISSUE THREAD

**Issue by PythonLinks** [SteffenReith/J1Sc#3]
I tried installing JDK 8, but could not find it on the web.  They redirect to JDK version 21.  So I installed that.  I hope it all works.

**Comment by PythonLinks** [comment]
# Security Manager is Deprecated. 


<details><summary>Here is the error message: </summary>
 

[info] [launcher] getting Scala 2.10.6 (for sbt)...
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release. 
<details><summary>The full log is below.  And it looked like it was going so well...</summary>




java -version
java version "21" 2023-09-19 LTS
Java(TM) SE Runtime Environment (build 21+35-LTS-2513)
Java HotSpot(TM) 64-Bit Server VM (build 21+35-LTS-2513, mixed mode, sharing)

bash-3.2$ scala -version
Scala code runner version 3.3.1 -- Copyright 2002-2023, LAMP/EPFL

bash-3.2$ sbt -version
 (error message deleted) 
sbt script version: 1.9.6

I am also trying to get sbt working with the default Spinal HDL project, that is also having trouble, reported elsewhere. 


bash-3.2$ cd J1Sc
bash-3.2$ sbt
[info] [launcher] getting org.scala-sbt sbt 0.13.16  (this may take some time)...
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar ...
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.6/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.16/jars/main.jar ...
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.6/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.16/jars/sbt.jar ...
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.6/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.16/jars/compiler-interface.jar ...
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.6/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.16/jars/io.jar ...
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.6/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.16/jars/interface.jar ...
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.6/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.16/jars/main-settings.jar ...
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.6/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.16/jars/actions.jar ...
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.6/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
	[SUCCESSFUL ] org.scala-lang#scala-library;2.10.6!scala-library.jar (4147ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.16/jars/ivy.jar ...
	[SUCCESSFUL ] org.scala-sbt#interface;0.13.16!interface.jar (8145ms)
	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.16!sbt.jar (8189ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.16/jars/logic.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.16/jars/logging.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.16!compiler-interface.jar (10195ms)
	[SUCCESSFUL ] org.scala-sbt#actions;0.13.16!actions.jar (10645ms)
	[SUCCESSFUL ] org.scala-sbt#io;0.13.16!io.jar (10700ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.16/jars/process.jar ...
	[SUCCESSFUL ] org.scala-sbt#main;0.13.16!main.jar (11324ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.16/jars/run.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.16/jars/command.jar ...
	[SUCCESSFUL ] org.scala-sbt#main-settings;0.13.16!main-settings.jar (11668ms)
	[SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.1!launcher-interface.jar (521ms)
	[SUCCESSFUL ] org.scala-sbt#ivy;0.13.16!ivy.jar (7709ms)
	[SUCCESSFUL ] org.scala-sbt#logic;0.13.16!logic.jar (4155ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.16/jars/classpath.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.16/jars/api.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.16/jars/completion.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.16/jars/compiler-integration.jar ...
	[SUCCESSFUL ] org.scala-sbt#logging;0.13.16!logging.jar (5152ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.16/jars/compiler-ivy-integration.jar ...
	[SUCCESSFUL ] org.scala-sbt#run;0.13.16!run.jar (4000ms)
	[SUCCESSFUL ] org.scala-sbt#process;0.13.16!process.jar (4469ms)
	[SUCCESSFUL ] org.scala-sbt#command;0.13.16!command.jar (4424ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.16/jars/relation.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.16/jars/task-system.jar ...
	[SUCCESSFUL ] org.scala-sbt#api;0.13.16!api.jar (3888ms)
	[SUCCESSFUL ] org.scala-sbt#classpath;0.13.16!classpath.jar (4134ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.16/jars/tasks.jar ...
	[SUCCESSFUL ] org.scala-sbt#completion;0.13.16!completion.jar (4343ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.16/jars/tracking.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.16/jars/testing.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-integration;0.13.16!compiler-integration.jar (4181ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.jar ...
	[SUCCESSFUL ] org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar (3533ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.16/jars/control.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.10.6!scala-reflect.jar (1197ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.16/jars/collections.jar ...
	[SUCCESSFUL ] org.scala-sbt#relation;0.13.16!relation.jar (3845ms)
downloading https://repo1.maven.org/maven2/jline/jline/2.14.4/jline-2.14.4.jar ...
	[SUCCESSFUL ] jline#jline;2.14.4!jline.jar (326ms)
	[SUCCESSFUL ] org.scala-sbt#task-system;0.13.16!task-system.jar (4199ms)
	[SUCCESSFUL ] org.scala-sbt#tasks;0.13.16!tasks.jar (4010ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.16/jars/classfile.jar ...
	[SUCCESSFUL ] org.scala-sbt#tracking;0.13.16!tracking.jar (3884ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.16/jars/incremental-compiler.jar ...
	[SUCCESSFUL ] org.scala-sbt#testing;0.13.16!testing.jar (3890ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.16/jars/compile.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.10.6!scala-compiler.jar (4063ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.16/jars/persist.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar ...
	[SUCCESSFUL ] org.scala-sbt#control;0.13.16!control.jar (3902ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.16/jars/cross.jar ...
	[SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4!ivy.jar (545ms)
downloading https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar ...
	[SUCCESSFUL ] com.jcraft#jsch;0.1.50!jsch.jar (333ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.jar ...
	[SUCCESSFUL ] org.scala-sbt#serialization_2.10;0.1.2!serialization_2.10.jar (341ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar ...
	[SUCCESSFUL ] org.scala-lang.modules#scala-pickling_2.10;0.10.1!scala-pickling_2.10.jar (518ms)
downloading https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.jar ...
	[SUCCESSFUL ] org.json4s#json4s-core_2.10;3.2.10!json4s-core_2.10.jar (386ms)
downloading https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.jar ...
	[SUCCESSFUL ] org.spire-math#jawn-parser_2.10;0.6.0!jawn-parser_2.10.jar (253ms)
downloading https://repo1.maven.org/maven2/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.jar ...
	[SUCCESSFUL ] org.scala-sbt#classfile;0.13.16!classfile.jar (4569ms)
downloading https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar ...
	[SUCCESSFUL ] org.spire-math#json4s-support_2.10;0.6.0!json4s-support_2.10.jar (272ms)
downloading https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.jar ...
	[SUCCESSFUL ] org.json4s#json4s-ast_2.10;3.2.10!json4s-ast_2.10.jar (367ms)
downloading https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar ...
	[SUCCESSFUL ] org.scalamacros#quasiquotes_2.10;2.0.1!quasiquotes_2.10.jar (426ms)
	[SUCCESSFUL ] org.scala-sbt#collections;0.13.16!collections.jar (6159ms)
	[SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.6!paranamer.jar (267ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar ...
	[SUCCESSFUL ] org.scala-sbt#persist;0.13.16!persist.jar (4580ms)
	[SUCCESSFUL ] org.scala-sbt#compile;0.13.16!compile.jar (5077ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar ...
	[SUCCESSFUL ] org.scala-sbt#test-interface;1.0!test-interface.jar (271ms)
	[SUCCESSFUL ] org.scala-sbt#cross;0.13.16!cross.jar (4122ms)
	[SUCCESSFUL ] org.scala-sbt#template-resolver;0.1!template-resolver.jar (259ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.16/jars/cache.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.16/jars/test-agent.jar ...
	[SUCCESSFUL ] org.scala-tools.sbinary#sbinary_2.10;0.4.2!sbinary_2.10.jar (5170ms)
	[SUCCESSFUL ] org.scala-sbt#incremental-compiler;0.13.16!incremental-compiler.jar (6040ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.16/jars/apply-macro.jar ...
	[SUCCESSFUL ] org.scala-sbt#test-agent;0.13.16!test-agent.jar (3604ms)
	[SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.16!apply-macro.jar (4213ms)
	[SUCCESSFUL ] org.scala-sbt#cache;0.13.16!cache.jar (4619ms)
:: retrieving :: org.scala-sbt#boot-app
	confs: [default]
	49 artifacts copied, 0 already retrieved
[info] [launcher] getting Scala 2.10.6 (for sbt)...
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at sbt.TrapExit$.installManager(TrapExit.scala:52)
	at sbt.StandardMain$.runManaged(Main.scala:60)
	at sbt.xMain.run(Main.scala:35)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release

</details>

**Comment by PythonLinks** [comment]
The previous posting was sent before I was done editing it.  So I have edited it with more details.

**Comment by Dolu1990** [comment]
Hmm  sbt 0.13.16 is reaaaaaly old, i would say, could try 1.6.0 ?
here you can update it : 
https://github.com/SteffenReith/J1Sc/blob/master/project/build.properties

About tje JVM, personnaly i'm on : 

```rawrr@rawrr-pc:~$ javac --version
javac 11.0.20.1
rawrr@rawrr-pc:~$ java --version
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

**Comment by PythonLinks** [comment]
Okay, so there are some 4 solutions to this.  You may be able to get the current versions to work.  I was not able to find such an old version of Java. 

What I did on Mac OS X is 
`
 java -version
openjdk version "17.0.8.1" 2023-08-24
scalaVersion := "2.12.16"
spinalVersion = "1.4.2"
sbt -version
sbt version in this project: 1.9.6
`
It runs, although I have not yet tested the bitstream. 
I do need to upgrade the SpinalHDL version.  reportedly not that hard to do, but I am still a bit scared of changing anything and breaking everything. 

The other option is to use the devel branch from Jan 2023.  It is This branch is [46 commits ahead](https://github.com/SteffenReith/J1Sc/compare/master...devel), [2 commits behind](https://github.com/SteffenReith/J1Sc/compare/devel...master) master.

**Comment by PythonLinks** [comment]
Sorry about that, it posted before I was done. 
The devel branch uses

scalaVersion := "2.11.12"
val spinalVersion = "1.8.0b"

So it is not clear to me which version I should be using.   master or devel?   @SteffenReith, which do you recommend I should be using? 

Best would be if you would do a merge, so that there would be no questions as to which to use.  Alternatively I could issue a pull request for the versions I am using.   Not a big change.  Two files, And I still have not tested it on hardware. 

I am busy figuring out which files I need to change to port to the pico-ice board.  Work is slower, now that school has started.
